#  牛客选择题---9月14日

##  1：

![image-20220914141355801](C:\Users\14776\AppData\Roaming\Typora\typora-user-images\image-20220914141355801.png) 

***

解析：

![image-20220914142715225](C:\Users\14776\AppData\Roaming\Typora\typora-user-images\image-20220914142715225.png) 

***

注意他这里是传的引用类型，所以你通过形参直接修改是会影响到实参的值的，但是如果你给形参赋值新的指向，是不会影响到实参的。

***

##  2：

![image-20220914143343047](C:\Users\14776\AppData\Roaming\Typora\typora-user-images\image-20220914143343047.png) 

***

解析：

A选项题目还是不严谨的，如果说抛出InterruptedException异常之后，捕获了的话程序是会继续执行的。如果没有捕获，那么就是交给JVM进行处理，那程序就直接终止了。

调用wait方法之后线程会释放锁，进入阻塞状态，之后等待别的线程调用notify()方法才能唤醒。

创建新的线程并不会导致已有执行线程终止。

高优先级线程进入就绪状态，就绪状态并不是说就有了CPU了，它也得等现有线程执行完了才能获取CPU，高优先级说明他相对于其他同处于优先级的线程来说更有机会获得到CPU。

***

##  3：

![image-20220914144539692](C:\Users\14776\AppData\Roaming\Typora\typora-user-images\image-20220914144539692.png) 

解析：

![image-20220914144520534](C:\Users\14776\AppData\Roaming\Typora\typora-user-images\image-20220914144520534.png) 

***

编译时异常在编译的时候就会发现，运行时异常需要运行的时候才会发现。注意上面的FileNotFoundExpection是继承自IOException的，所以也是编译时异常。

***

